version: "3.7"

services:
    socat-warp:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: on-failure
        user: root
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        network_mode: host
        extra_hosts:
            - "host.docker.internal:host-gateway"
