version: "3.7"

services:
    acme.sh:
        build:
            context: ./../acmesh
            dockerfile: Dockerfile
        ports:
            - "80:80/tcp"
        volumes:
            - ./../cert:/cert
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        env_file: .env
        environment:
            - "RELOADCMD=docker restart ss-nginx"

    nginx:
        container_name: ss-nginx
        image: nginx:alpine
        volumes:
            - ./nginx/templates:/etc/nginx/templates:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/wait-for-cert.sh:/wait-for-cert.sh
            - ./../cert:/etc/nginx/cert:ro
        restart: on-failure
        ports:
            - "443:443/tcp"
        env_file: .env
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        entrypoint: ["/wait-for-cert.sh", "/docker-entrypoint.sh", "nginx"]

    ss-server:
        build:
            context: ./../ssserver
            dockerfile: Dockerfile
        command:
            - "/start-ss.sh"
        volumes:
            - ./../ssserver/start-ss.sh:/start-ss.sh:ro
        restart: on-failure
        env_file: .env
        user: root
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
