version: "3.7"

services:
    # nginx:
    #     image: nginx:alpine
    #     volumes:
    #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - "${KCP_PORT}:${KCP_PORT}/udp"
    #     restart: on-failure
    #     env_file: .env
    #     user: root
    #     ulimits:
    #         nofile:
    #             soft: 65536
    #             hard: 65536

    ss-server:
        build:
            context: ./../ssserver
            dockerfile: Dockerfile
        ports:
            - "${PORT}:16384/udp"
        command:
            - "/start-kcp.sh"
        volumes:
            - ./../ssserver/start-kcp.sh:/start-kcp.sh:ro
        restart: on-failure
        env_file: .env
        user: root
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
