version: "3.7"

services:
    vless:
        build:
            context: ./../xray
            dockerfile: Dockerfile
        ports:
            - "${PORT}:16834/udp"
        command:
            - "/start-xray.sh"
        volumes:
            - ./config.json:/config.json
            - /var/run/docker.sock:/var/run/docker.sock
        restart: on-failure
        user: root
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
