version: "3.7"

services:
    acme.sh:
        build:
            context: ./../acmesh
            dockerfile: Dockerfile
        ports:
            - "80:80/tcp"
        volumes:
            - ./../cert:/cert
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        env_file: .env
        environment:
            - "RELOADCMD=docker restart vless"

    vless:
        build:
            context: ./../xray
            dockerfile: Dockerfile
        ports:
            - "443:443/tcp"
        command:
            - "/start-xray.sh"
        volumes:
            - ./../cert:/cert
            - ./config.json:/config.json
            - /var/run/docker.sock:/var/run/docker.sock
        restart: on-failure
        user: root
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
